[package]
name = "kioku"
version = "0.3.1"
description = "A memory arena"
documentation = "https://docs.rs/kioku"
repository = "https://github.com/cessen/kioku"
readme = "README.md"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
